# ================================ DEFINES ==================================
from __future__ import annotations  # TYPE HINTS

from pathlib import Path  # PATHS

# ================================= PATHS ====================================
PROJECT_DIR = Path(__file__).resolve().parent  # ROOT
DATA_DIR = PROJECT_DIR / "data"  # DATA DIR
A_DATA_DIR = DATA_DIR  # A MATRIX DATA DIR
OUT_DIR = PROJECT_DIR / "out"  # OUT DIR
CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"  # MODEL DIR

# ================================ COMMANDS =================================
COMMANDS = [  # CLI MODES
    "single-matrix",  # AE DMD SINGLE
    "multi-matrix",  # AE DMD MULTI
    "ae-only-single",  # AE ONLY SINGLE
    "ae-only-multi",  # AE ONLY MULTI
    "dmd-only-single",  # DMD ONLY SINGLE
    "dmd-only-multi",  # DMD ONLY MULTI
    "ae-matrix-predict",  # AE READ MATRIX RECON PREDICT
]

# ============================== MANDELBROT BOX =============================
C_RE_MIN = -0.05  # RE MIN
C_RE_MAX = 0.05  # RE MAX
C_IM_MIN = -0.05  # IM MIN
C_IM_MAX = 0.05  # IM MAX
ESCAPE_R = 2.0  # ESCAPE -- CLASSIFICATION / VISUALIZATION THRESHOLD ONLY, DO NOT USE FOR CLAMPING

DYNAMICS_CLAMP_R = 100.0  # NUMERICAL SAFETY BOUND DURING ITERATION -- NOT A DECISION THRESHOLD
TRAIN_MAX_ITERS = 40  # TRAIN STEPS
PREDICT_EXTRA_STEPS = 1  # NEXT STEPS
PREDICT_ROLLOUT_CHECK_STEPS = 10  # HOW MANY ROLLOUT STEPS TO REPORT REL-L2 FOR (MADE EXPLICIT, WAS getattr-ONLY)

# ======================= TRAINING-DATA FILTERING (NEW) ======================

FILTER_ESCAPED_FOR_TRAINING = True  # DROP TRAJECTORIES THAT ESCAPE BY TRAIN_MAX_ITERS FROM X1/X2
KEEP_ESCAPED_FRACTION = 0.0  # 0.0 = fikl's BEHAVIOUR (FULLY EXCLUDE ESCAPED TRAJECTORIES)
# ============================== SINGLE MATRIX ===============================
SINGLE_MATRIX_SOURCE = "emotion"  # SOURCE
SINGLE_MATRIX_INDEX = 7  # MATRIX ID
SINGLE_MATRIX_C_RE_N = 128  # RE RES
SINGLE_MATRIX_C_IM_N = 128  # IM RES

# =============================== MULTI MATRIX ===============================
MULTI_MATRIX_SOURCE = "emotion"  # SOURCE
MULTI_MATRIX_TRAIN_COUNT = 10  # TRAIN COUNT
MULTI_MATRIX_TEST_COUNT = 2  # TEST COUNT
MULTI_MATRIX_SPLIT_SEED = 0  # SPLIT SEED
MULTI_MATRIX_C_RE_N = 128  # SAFE RE RES
MULTI_MATRIX_C_IM_N = 128  # SAFE IM RES
MULTI_MATRIX_SAVE_FULL_FIRST = True  # SAVE SAMPLE

# =============================== AE SETTINGS ================================
LATENT_DIM = 256  # LATENT
AE_EPOCHS = 60  # EPOCHS
AE_ONLY_EPOCHS = 60 # EPOCHS
AE_BATCH_SIZE = 2048  # BATCH
AE_LR = 1e-4  # LR
AE_REC_WEIGHT = 1.0  # REC LOSS
AE_PRED_WEIGHT = 2.0  # PRED LOSS
AE_LATENT_WEIGHT = 0.5  # LATENT LOSS
AE_PRED_USE_ALIVE_ONLY = True  # FILTER

AE_LOSS_AUTO_SCALE = True  # DIVIDE LOSS BY mean(X1**2) SO IT'S SCALE-INVARIANT

AE_USE_LR_SCHEDULER = True  # ENABLE ReduceLROnPlateau ON THE TRAIN LOSS
AE_LR_PATIENCE = 5  # EPOCHS WITH NO IMPROVEMENT BEFORE DROPPING LR
AE_LR_FACTOR = 0.5  # MULTIPLY LR BY THIS ON PLATEAU
AE_LR_MIN = 1e-6  # FLOOR

# ========================== VALIDATION SPLIT (NEW) ==========================
AE_VAL_FRACTION = 0.1  # FRACTION OF (ALREADY-FILTERED, ALIVE-ONLY) PAIRS HELD OUT PER BLOCK
AE_VAL_SEED = 0  # REPRODUCIBLE SPLIT
AE_EARLY_STOP_PATIENCE = 0  # EPOCHS OF NO VAL IMPROVEMENT BEFORE STOPPING EARLY; 0 = OFF (fikl's DEFAULT)

# ============================ AE-ONLY PREDICTOR ==============================
AE_PRED_LATENT_DIM = LATENT_DIM  # LATENT SIZE FOR THE AE-ONLY PREDICTOR
AE_PRED_EPOCHS = AE_ONLY_EPOCHS  # EPOCHS FOR THE AE-ONLY PREDICTOR
AE_ONLY_BATCH_SIZE = AE_BATCH_SIZE  # BATCH SIZE FOR THE AE-ONLY PREDICTOR
AE_ONLY_LR = AE_LR  # LR FOR THE AE-ONLY PREDICTOR
AE_PRED_TRAIN_CLIP_R = DYNAMICS_CLAMP_R  # CLAMP USED WHILE BUILDING ITS TRAINING DATA (NOT THE CLASSIFY THRESHOLD)

AE_USE_QUADRATIC_PREDICTOR = False  # TOGGLE: USE quadratic_predictor.QuadraticPredictor INSTEAD OF Encoder/Decoder
AE_QUADRATIC_RANK = None  # None = FULL d x d COUPLING MATRIX; INT = LOW-RANK U V FACTORISATION

# =============================== DMD SETTINGS ===============================
DMD_RIDGE = 1e-2  # RIDGE
DMD_FIT_BATCH_SIZE = 65536  # FIT BATCH
AE_ENCODE_BATCH_SIZE = 65536  # ENCODE BATCH
PREDICT_BATCH_SIZE = 4096  # PREDICT BATCH

# ============================== DISPLAY SAVE ================================
IMAGE_SCALE = 4  # UPSCALE
LOSS_DPI = 160  # DPI
SAVE_CSV_DMD = True  # SAVE CSV

LOSS_CURVES_LOG_SCALE = True  # DEFAULT y-AXIS SCALE FOR save_loss_curve

# ================================ DEVICE ====================================
USE_CUDA_IF_AVAILABLE = True  # GPU FLAG

#=============V26=================